workspace("vulcain")
configurations({"Debug", "Release"})
location("build")

-- Library
project("vulcain")
kind("StaticLib")
toolset("clang")
language("C")
targetdir("bin")
buildoptions({"-Wall", "-Werror", "-g"})
libdirs({"third_party/vma/"})
includedirs({"third_party/vma/"})
links({"m", "vulkan", "vma"})
files({"src/**.c"})

-- Playground
project("vulcain_pg")
kind("ConsoleApp")
language("C")
toolset("clang")
targetdir("bin")
buildoptions({"-Wall", "-Werror", "-g"})
dependson({"libvulcain"})
libdirs({"bin/"})
libdirs({"third_party/vma/"})
links({"m", "vulcain", "glfw", "vulkan", "vma", "stdc++"})
includedirs({"third_party/vma/", "src/"})
files({"pg/**.c","pg/**.h"})
