workspace("vulcain")
configurations({"Debug", "Release"})
location("build")

project("vulcain")
kind("ConsoleApp")
language("C")
targetdir("bin")
buildoptions({"-Wall", "-Werror", "-g"})
toolset("clang")
libdirs({"third_party/vma/lib", "third_party/stb"})
includedirs({"third_party/vma/include", "third_party/fast_obj/", "third_party/mathc", "third_party/stb"})
links({"glfw", "m", "pthread", "vulkan", "dl", "rt", "X11", "Xxf86vm", "Xrandr", "Xi", "vma", "stdc++", "img"})

files({"src/**.c","src/**.h", "third_party/fast_obj/**.c", "third_party/mathc/**.c"})
