workspace("vulcain")
configurations({"Debug", "Release"})
location("build")

-- Library
project("vulcain")
kind("StaticLib")
toolset("clang")
language("C")
targetdir("bin")
buildoptions({"-Wall", "-Werror", "-g"})
libdirs({"third_party/vma/", "third_party/cimgui"})
includedirs({"third_party/vma/", "third_party/cimgui"})
links({"m", "vulkan", "vma", "cimgui"})
files({"src/**.c"})

-- Playground
project("vulcain_pg")
kind("ConsoleApp")
language("C")
toolset("clang")
targetdir("bin")
buildoptions({"-Wall", "-Werror", "-g"})
dependson({"libvulcain"})
libdirs({"bin/","third_party/cimgui"})
libdirs({"third_party/vma/", "third_party/cimgui"})
links({"m", "vulcain", "glfw", "vulkan", "vma", "stdc++", "cimgui"})
includedirs({"third_party/vma/", "src/", "third_party/cimgui"})
files({"pg/**.c","pg/**.h"})
